version: '3.8'
services:
  springboot-docker-container:
    image: springboot-docker-container
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/banking3
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      BEZKODER_APP_JWTSECRET: bezKoderSecretKey
      BEZKODER_APP_JWTEXPIRATIONMS: "86400000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: banking3
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
